## **NumPy**

**Basic NumPy Arrays**

---



In [1]:
import sys
import numpy as np

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
b = np.array([0,-5,1,1.5,2])

In [ ]:
a[0],a[1]

(1, 2)

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
b

array([ 0. , -5. ,  1. ,  1.5,  2. ])

In [ ]:
b[0],b[2],b[-1]

(0.0, 1.0, 2.0)

In [ ]:
b[[0,2,-1]]

array([0., 1., 2.])

**Array Types**

---



In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b

array([ 0. , -5. ,  1. ,  1.5,  2. ])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
np.array([1,2,3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [ ]:
np.array([1,2,3,4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [ ]:
c = np.array(['a','b','c'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a':1}, sys])

In [ ]:
d.dtype

dtype('O')

**Dimensions and Shapes**

---



In [3]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A.shape

(2, 3)

In [ ]:
A.size

6

In [ ]:
A.ndim

2

In [38]:
arr = np.array([1,2,3])
arr.shape

(3,)

**If the shape isn't consistent, it'll just fall back to regular python objects**

In [ ]:
B = np.array([
    [
      [11,12,13],
      [14,15,16]
    ],
    [
       [6,7,8],
       [10,5,9]
    ]
])

In [ ]:
B.dtype

dtype('int64')

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.size

12

In [ ]:
B.ndim

3

In [ ]:
C = np.array([
    [
      [9,3,1],
      [14,15,16]
    ],
    [
       [2,3,5]
    ]
], dtype=object)

In [ ]:
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
C.ndim

1

In [ ]:
type(C[0])

list

**Indexing and Slicing of Matrcies**

---



In [ ]:
#Square Matrix
A = np.array([
  #  0.1.2
    [1,2,3],  #0
    [4,5,6],  #1
    [7,8,9]   #2
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[0][1]

2

In [ ]:
A[1][0]

4

In [ ]:
A[1,0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2,2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10,11,12])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [99, 99, 99]])

**Summer Statistics**

---




In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
a.sum()

10

In [ ]:
a.min()

1

In [ ]:
a.max()

4

In [ ]:
A

array([[ 1,  2,  3],
       [10, 11, 12],
       [99, 99, 99]])

In [ ]:
A.mean()

37.333333333333336

In [ ]:
A.std()

43.764521399569006

In [ ]:
A.sum()

336

In [ ]:
A.sum(axis=0)  #sum of columns

array([110, 112, 114])

In [ ]:
A.sum(axis=1)  #sum of rows

array([  6,  33, 297])

In [ ]:
A.mean(axis=0)

array([36.66666667, 37.33333333, 38.        ])

In [ ]:
A.mean(axis=1)

array([ 2., 11., 99.])

In [ ]:
A.std(axis=0)

array([44.22920101, 43.75944343, 43.28972164])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.        ])

**Broadcasting and Vectorized operations**

---



In [ ]:
import numpy as np
import sys

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
a + 10

array([110, 111, 112, 113])

In [ ]:
l = [0,1,2,3]

In [ ]:
[i*10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10,10,10,10])

In [ ]:
b

array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

In [ ]:
a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 20

array([20, 21, 22, 23, 24])

**Boolean Arrays**

---



(*Also called masks)*


In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[[0,-1]]  #multi-index

array([0, 3])

In [ ]:
a[0],a[-1]  #regular python

(0, 3)

In [ ]:
a[[True,False,False,True]]  #boolean array

array([0, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a >= a.mean()]

array([2, 3])

In [ ]:
a[~(a >= a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3,3))

In [ ]:
A

array([[ 3, 85, 32],
       [69, 36, 54],
       [45,  4,  3]])

In [ ]:
A > 30

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [ ]:
A [A > 30]

array([85, 32, 69, 36, 54, 45])

In [ ]:
A[np.array([
    [False,  True,  True],
    [ True,  True,  True],
    [ True, False, False]
])]

array([85, 32, 69, 36, 54, 45])

In [ ]:
a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
print(a <= 3)

[ True  True  True  True False]


**Linear Algebra**

---



In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [ ]:
A.dot(B)   #dot product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B      #cross product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B. T       #B transpose

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
A. T       #A transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
B. T @ A

array([[36, 48, 60],
       [24, 33, 42]])

**Size of objects in memory**

---



**Int, float**

In [ ]:
#An integer in python is > 24bytes
sys.getsizeof(1)

28

In [ ]:
#Longs are even larger
sys.getsizeof(10**100)

72

In [ ]:
#NumPy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(float).itemsize

8

**Lists are even larger**


In [ ]:
#A one-element list
sys.getsizeof([1])

64

In [ ]:
#An array of one element in NumPy
np.array([1]).nbytes

8

**And perfomance is also important**


In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 583 µs, sys: 0 ns, total: 583 µs
Wall time: 607 µs


332833500

In [ ]:
%time np.sum(a ** 2)

CPU times: user 160 µs, sys: 16 µs, total: 176 µs
Wall time: 182 µs


332833500

**Useful NumPy functions**

---



***random***






In [ ]:
np.random.random(size=2)

array([0.21466652, 0.93764095])

In [ ]:
np.random.normal(size=2)

array([-0.35534972,  1.08452259])

In [ ]:
np.random.rand(2,4)

array([[0.3561467 , 0.65683506, 0.21205921, 0.37700576],
       [0.71497074, 0.77969112, 0.78645591, 0.87219415]])

***arange***

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2,5)

array([2, 3, 4])

In [ ]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

***reshape***

In [ ]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

***linspace***

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,1,20)   #stop value(1) is included

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0,1,20,False)   #endpoint=False i.e stop value(1) is not included

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

***zeros, ones, empty***

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

**identity and eye**

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World" [6]

'W'

In [ ]:
"Maryam" [3]

'y'

**The Basics**

---



In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([
    [9.0,8.0,7.0],
    [6.0,5.0,4.0]
])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#Get Dimensions
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
#Get shape
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

In [ ]:
a.dtype

dtype('int16')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
#Get size
a.itemsize    #int contains 16 bytes here i.e 8*2

2

In [ ]:
b.itemsize    #float contains 64 bytes here i.e 2 8*8

8

In [ ]:
a.size

3

In [ ]:
b.size

6

In [ ]:
#Get total size
a.nbytes     #a.size * a.itemsize

6

In [4]:
b.nbytes

48

**Accessing/Changing specific elements, rows, columns, etc**

---



In [21]:
a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.shape

(2, 7)

In [ ]:
#Get a specific element [r, c]
a[1,5]

13

In [ ]:
a[1,-2]

13

In [ ]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
#Get a specific column
a[:, 5]

array([ 6, 13])

In [ ]:
a[:, 3]

array([ 4, 11])

In [ ]:
#Getting a little more fancy [startindex:stopindex:stepindex]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
#changing elements
a[1,5] = 20

In [ ]:
a[0,-1] = 14

In [ ]:
print(a)

[[ 1  2  3  4  5  6 14]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6 14]
 [ 8  9  5 11 12 20 14]]


In [ ]:
a[:, 4] = [1,2]
print(a)

[[ 1  2  5  4  1  6 14]
 [ 8  9  5 11  2 20 14]]


**3-D example**



In [ ]:
b = np.array([
    [[1,2],
    [3,4]],
    [[5,6],
    [7,8]]
])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element (work outside in)
b[0,1,1]

4

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
b[:,:,0]

array([[1, 3],
       [5, 7]])

In [ ]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

In [ ]:
a[:,2] = 20
print(a)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]


**Initializing Different Types of Arrays**

---



In [2]:
import numpy as np
import sys

In [3]:
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [10]:
#All 1's matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [17]:
#Any other number  full()
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [19]:
np.full((3,3), 99, dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [22]:
#Any other number  full_like()
np.full_like(a, 4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
#random decimal numbers
np.random.rand(4,2)

array([[0.57227714, 0.01763289],
       [0.42669271, 0.09851185],
       [0.39826439, 0.09951577],
       [0.72643256, 0.6653388 ]])

In [25]:
np.random.rand(4,2,3)

array([[[0.87258079, 0.34640079, 0.93041931],
        [0.23131481, 0.77123628, 0.76815983]],

       [[0.38868068, 0.51957747, 0.68405325],
        [0.0638406 , 0.60887208, 0.75404321]],

       [[0.72921639, 0.08382018, 0.51618924],
        [0.65047693, 0.10228737, 0.12424737]],

       [[0.75616499, 0.15348816, 0.3312202 ],
        [0.78645271, 0.97882968, 0.74426039]]])

In [26]:
np.random.random_sample(a.shape)

array([[0.68858287, 0.82605863, 0.01117703, 0.41276312, 0.908583  ,
        0.25397835, 0.57044158],
       [0.94578708, 0.01174805, 0.519005  , 0.69873066, 0.94718703,
        0.70570179, 0.67350535]])

In [37]:
#random integer values
np.random.randint(100)

80

In [32]:
np.random.randint(10, size=(3,2))

array([[1, 5],
       [5, 3],
       [7, 8]])

In [39]:
np.random.randint(-4,8, size=(3,3))

array([[-4, -1,  3],
       [-2, -1, -3],
       [ 7,  1,  5]])

In [41]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] =  z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [93]:
output = np.zeros((7,7))
print(output)

z = np.ones((5,5))
z[2,2] = 5
print(z)

output[1:-1,1:-1] = z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [100]:
#Be careful when copying arrays!!!
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)
print(b)

[100   2   3]
[100   2   3]


In [104]:
#To prevent this
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


**Mathematics**

---



In [107]:
a + 2

array([3, 4, 5, 6])

In [108]:
a - 2

array([-1,  0,  1,  2])

In [109]:
a * 2

array([2, 4, 6, 8])

In [110]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [112]:
a += 2  #value of 'a' changes
a

array([5, 6, 7, 8])

In [113]:
a + 3

array([ 8,  9, 10, 11])

In [114]:
b = np.array([1,0,1,0])

In [115]:
a + b

array([6, 6, 8, 8])

In [117]:
a ** 2

array([25, 36, 49, 64])

In [118]:
#Take the sin
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [119]:
#Take the cos
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

https://numpy.org/doc/stable/reference/routines.math.html

**Linear Algebra**

---



In [127]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [131]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

https://numpy.org/doc/stable/reference/routines.linalg.html

**Statistics**

---



In [133]:
stats = np.array([
    [1,2,3],
    [4,5,6]
])
print(stats)

[[1 2 3]
 [4 5 6]]


In [138]:
np.min(stats, axis=1)  #min of first and second row

array([1, 4])

In [140]:
np.max(stats, axis=0)

array([4, 5, 6])

In [137]:
np.mean(stats)

3.5

In [142]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [143]:
np.sum(stats, axis=1)

array([ 6, 15])

In [8]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.max(a, axis=1)
print(b)

c = np.max(a, axis=1).sum()
print(c)

[3 6]
9


**Reorganizing Arrays**

---


In [9]:
before = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(before)

after = before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [168]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(v1)
print(v2)

np.vstack([v1, v2, v2, v2])

[1 2 3 4]
[5 6 7 8]


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [173]:
#Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

np.hstack([h1, h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

---

##### **Reverse array**

In [2]:
#Reverse array
arr = np.array([1,2,3,4])
reverse_arr = arr[::-1]
print(reverse_arr)

[4 3 2 1]


In [3]:
#Reverse array in float using astype()
arr = np.array([1,2,3,4])
reverse_arr = arr[::-1]
reverse_arr = reverse_arr.astype(float)
print(reverse_arr)

[4. 3. 2. 1.]


**Load Data from File**

---



In [ ]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')
filedata

**Boolean Masking and Advanced Indexing**

In [ ]:
filedata > 50

In [ ]:
filedata[filedata > 50]

In [ ]:
np.any(filedata > 50, axis = 0)

In [ ]:
np.all(filedata > 50, axis = 1)

In [ ]:
((filedata > 50) & (filedata < 100))

In [ ]:
(~(filedata > 50) & (filedata < 100))

In [187]:
#You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,-1]]

array([2, 3, 9])

**Indexing Questions**

---

In [189]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]
])

In [190]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [192]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [193]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

---

In [ ]:
#to see what the function does
help(np.dot)

In [ ]:
#python array
arr1 = list(range(100))
arr1

In [18]:
#numpy array
a = np.array(arr1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
%%time

result = 0
for i,j in zip(arr1, arr2):
    result += i*j
result

In [ ]:
%%time

np.dot(arr1,arr2)

In [41]:
#matrix multiplication 
climate_data = np.array([
    [1,2,3],
    [6,7,8],
    [11,12,13],
    [16,17,18],
    [21,22,25]
])

weights = np.array([1.0,2.0,3.0])

np.matmul(climate_data, weights)  #OR    climate_data @ weights    (both gives same answer)

array([ 14.,  44.,  74., 104., 140.])

In [50]:
a = np.array([1.5,2.9,3.0,4.9,8.0])
b = np.array([2,3,4,5,67])


array([2., 3., 3., 5., 8.])

In [51]:
np.median(a)

3.0

In [54]:
np.round(a)

array([2., 3., 3., 5., 8.])

In [57]:
np.arange(3) + 5

array([5, 6, 7])

In [59]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [60]:
np.random.rand(5)   #value between 0 to 1

array([0.88896324, 0.53125838, 0.91847651, 0.11808423, 0.46312202])

In [61]:
np.random.randn(2,3)   #values  from gaussian distribution

array([[ 0.29124222,  0.52691607, -0.65020369],
       [-0.46288946,  1.3017444 , -0.56546534]])

In [71]:
np.arange(10,90,3)      #(start : stop(exclusive) : step)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [67]:
np.arange(10,90,3).shape

(27,)

In [68]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [69]:
np.linspace(3,27,9)        #(start : stop : no_of_elements)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [4]:
#Element-wise operations
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result)

[5 7 9]


### **Missing Data**

In [1]:
#all values below are considered 'falsy'
falsy_values = (0, False, None, '', [], {})

In [3]:
any(falsy_values)   #any() - if iterable is empty return False o.w True

False

##### Numpy has a special "nullable" value for numbers which is np.nan    NaN: "Not a number"

In [6]:
np.nan

nan

##### The np.nan value is kind of a virus. Everything that it touches becomes np.nan

In [7]:
3 + np.nan

nan

In [9]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [10]:
a.sum()

nan

In [11]:
a.mean()

nan

##### This is better than regular None values, which in the previous examples would have raised an exception

In [ ]:
3 + None

##### For a numeric array, the **None** value is replaced by **np.nan**

In [14]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype = 'float')
a

array([ 1.,  2.,  3., nan, nan,  4.])

##### As np.nan is like a virus. If any nan value is in an array and you try to perform an operation on it, you'll get unexpected results

In [15]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [16]:
a.mean()

nan

In [17]:
a.sum()

nan

##### Numpy also supports an "Infinite" type

In [18]:
np.inf

inf

##### inf also behaves as a virus

In [19]:
3 + np.inf

inf

In [20]:
np.inf / 3

inf

In [21]:
np.inf / np.inf

nan

In [23]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype = 'float')

In [24]:
b.sum()

nan

### **Checking for nan or inf**

##### There are two functions: np.isnan and np.isinf that will perform the desired checks

In [25]:
np.isnan(np.nan)

True

In [30]:
np.isinf(np.inf)

True

##### And the joint operation can be performed with np.isfinite

In [31]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

##### np.isnan and np.isinf also take arrays as inputs, and return boolean arrays as results

In [32]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [33]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [34]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

##### **Note**: It's not so common to find infinite values. So, most of time keep working with only np.nan

### **Filtering them out**

##### Whenever you're trying to perform an operation with a Numpy array and you know there might be missing values, you'll need to filter them out before proceeding, to avoid nan propagation.

In [36]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [39]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

##### Which is equivalent to:

In [40]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

##### And with that result, all the operation can be now performed:

In [41]:
a[np.isfinite(a)].sum()

10.0

In [42]:
a[np.isfinite(a)].mean()

2.5

In [43]:
a[np.isfinite(a)].min()

1.0

In [44]:
a[np.isfinite(a)].max()

4.0

##### Checking whether the matrix can be multiplied or not

In [1]:
import numpy as np

def can_matrices_be_multiplied (matrix1, matrix2):
    rowsMat1, columnsMat1 = matrix1.shape
    rowsMat2, columnsMat2 = matrix2.shape

    if _____ == ______ :
        print('The matrices can be multipled!')
        return True
    else:
        return False